### ISSUE TITLE
VKontakteStrategy - object is not a function

### ISSUE THREAD

**Issue by falconsapsan** [stevebest/passport-vkontakte#18]
```
VKontakteStrategy = require('passport-vkontakte'),
....

passport.use(new VKontakteStrategy({
	    clientID:     VKONTAKTE_APP_ID, 
	    clientSecret: VKONTAKTE_APP_SECRET,
	    callbackURL:  "https://local:8081/auth/vkontakte/callback"
	  },
	  function(accessToken, refreshToken, profile, done) {
		    // asynchronous verification, for effect...
		    process.nextTick(function () {

		      // To keep the example simple, the user's Facebook profile is returned to
		      // represent the logged-in user.  In a typical application, you would want
		      // to associate the Facebook account with a user record in your database,
		      // and return that user instead.
		      return done(null, profile);
		    });
		  }
		));
```

When start apps:
```
/home/app.js:349
	passport.use(new VKontakteStrategy({
	             ^
TypeError: object is not a function
    at Object.<anonymous> (/home/app.js:349:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.runMain [as _onTimeout] (module.js:501:10)
    at Timer.listOnTimeout (timers.js:110:15)
```
what could be wrong?

**Comment by falconsapsan** [comment]
Sorry, there was a typo in the code before loading the module
