### ISSUE TITLE
example/login не работает

### ISSUE THREAD

**Issue by borapop** [stevebest/passport-vkontakte#46]
После авторизации выдает ошибку
API версии 5.0, 5.17 и 5.63 (последняя)

@stevebest возможно ли обновить example?

package.json:
```
{
  "name": "passport-vkontakte-examples-login",
  "version": "0.0.0",
  "dependencies": {
    "cookie-parser": "^1.4.3",
    "ejs": "2.5.1",
    "express": "4.14.0",
    "express-session": "^1.15.6",
    "passport": "0.3.2"
  },
  "scripts": {
    "start": "node app"
  }
}
```

```Error
   at Strategy.OAuth2Strategy.parseErrorResponse (/Users/borapop/passport-vkontakte/node_modules/passport-oauth2/lib/strategy.js:329:12)
   at Strategy.parseErrorResponse (/Users/borapop/passport-vkontakte/lib/strategy.js:197:54)
   at Strategy.OAuth2Strategy._createOAuthError (/Users/borapop/passport-vkontakte/node_modules/passport-oauth2/lib/strategy.js:376:16)
   at /Users/borapop/passport-vkontakte/node_modules/passport-oauth2/lib/strategy.js:166:45
   at /Users/borapop/passport-vkontakte/node_modules/oauth/lib/oauth2.js:191:18
   at passBackControl (/Users/borapop/passport-vkontakte/node_modules/oauth/lib/oauth2.js:132:9)
   at IncomingMessage.<anonymous> (/Users/borapop/passport-vkontakte/node_modules/oauth/lib/oauth2.js:157:7)
   at emitNone (events.js:91:20)
   at IncomingMessage.emit (events.js:185:7)
   at endReadableNT (_stream_readable.js:974:12)```

**Comment by stevebest** [comment]
Я обновил `package.json` примера. Теперь его можно запустить, если выполнить:

```
git clone https://github.com/stevebest/passport-vkontakte.git
cd passport-vkontakte
npm install
cd examples/login
npm install
VK_APP_ID=...... VK_APP_SECRET=..... node ./app.js
open http://localhost:3000
```

Убедитесь, что настройки вашего приложения в ВК выглядят вот так:

![passport vkontakte create app](https://user-images.githubusercontent.com/235527/31874031-32240706-b7f1-11e7-81b9-3c66320398b2.png)


![passport vkontakte](https://user-images.githubusercontent.com/235527/31873860-21799a8e-b7f0-11e7-8f17-71a1f75a0bfc.png)

**Comment by borapop** [comment]
@stevebest спасибо!
